import React from 'react'
import { View, Text } from '@react-pdf/renderer'
import { pdfStyles } from '../styles'

export function PdfFooter() {
  return (
    <View style={pdfStyles.footer} fixed>
      <Text style={pdfStyles.footerText}>
        Generated by Kalpak Design Studio Admin on {new Date().toLocaleDateString('en-IN')}
      </Text>
      <Text style={pdfStyles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
    </View>
  )
}
