// This file is auto-generated by Supabase CLI.
// Run: supabase gen types typescript --project-id vdujrflruolueslwnjpb > packages/db/src/types/database.types.ts
// Do not edit manually — re-generate after schema changes.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string
          email: string
          phone: string | null
          role: 'partner' | 'employee'
          avatar_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          full_name: string
          email: string
          phone?: string | null
          role: 'partner' | 'employee'
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string
          phone?: string | null
          role?: 'partner' | 'employee'
          avatar_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      clients: {
        Row: {
          id: string
          full_name: string
          email: string | null
          phone: string
          city: string | null
          source: 'website_form' | 'referral' | 'direct' | 'social_media' | 'other' | null
          lead_status: 'new' | 'contacted' | 'meeting_scheduled' | 'proposal_sent' | 'won' | 'lost'
          notes: string | null
          budget_range: string | null
          project_type: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email?: string | null
          phone: string
          city?: string | null
          source?: 'website_form' | 'referral' | 'direct' | 'social_media' | 'other' | null
          lead_status?: 'new' | 'contacted' | 'meeting_scheduled' | 'proposal_sent' | 'won' | 'lost'
          notes?: string | null
          budget_range?: string | null
          project_type?: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string | null
          phone?: string
          city?: string | null
          source?: 'website_form' | 'referral' | 'direct' | 'social_media' | 'other' | null
          lead_status?: 'new' | 'contacted' | 'meeting_scheduled' | 'proposal_sent' | 'won' | 'lost'
          notes?: string | null
          budget_range?: string | null
          project_type?: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          name: string
          client_id: string | null
          description: string | null
          project_type: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          status: 'lead' | 'confirmed' | 'in_progress' | 'snagging' | 'completed' | 'on_hold'
          city: string | null
          address: string | null
          total_budget: number | null
          start_date: string | null
          expected_end_date: string | null
          actual_end_date: string | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          client_id?: string | null
          description?: string | null
          project_type?: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          status?: 'lead' | 'confirmed' | 'in_progress' | 'snagging' | 'completed' | 'on_hold'
          city?: string | null
          address?: string | null
          total_budget?: number | null
          start_date?: string | null
          expected_end_date?: string | null
          actual_end_date?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          client_id?: string | null
          description?: string | null
          project_type?: 'residential' | 'commercial' | 'office' | 'hospitality' | 'other' | null
          status?: 'lead' | 'confirmed' | 'in_progress' | 'snagging' | 'completed' | 'on_hold'
          city?: string | null
          address?: string | null
          total_budget?: number | null
          start_date?: string | null
          expected_end_date?: string | null
          actual_end_date?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'projects_client_id_fkey'
            columns: ['client_id']
            isOneToOne: false
            referencedRelation: 'clients'
            referencedColumns: ['id']
          }
        ]
      }
      project_assignments: {
        Row: {
          id: string
          project_id: string
          user_id: string
          role_in_project: 'lead_partner' | 'supporting_partner' | 'lead_employee' | 'supporting_employee' | null
          assigned_at: string
          assigned_by: string | null
        }
        Insert: {
          id?: string
          project_id: string
          user_id: string
          role_in_project?: 'lead_partner' | 'supporting_partner' | 'lead_employee' | 'supporting_employee' | null
          assigned_at?: string
          assigned_by?: string | null
        }
        Update: {
          id?: string
          project_id?: string
          user_id?: string
          role_in_project?: 'lead_partner' | 'supporting_partner' | 'lead_employee' | 'supporting_employee' | null
          assigned_at?: string
          assigned_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'project_assignments_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_assignments_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      workers: {
        Row: {
          id: string
          full_name: string
          phone: string
          trade: 'electrician' | 'carpenter' | 'painter' | 'plumber' | 'mason' | 'tiler' | 'fabricator' | 'false_ceiling' | 'ac_hvac' | 'glass_works' | 'polisher' | 'general_labour' | 'supervisor' | 'other'
          is_active: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          phone: string
          trade: 'electrician' | 'carpenter' | 'painter' | 'plumber' | 'mason' | 'tiler' | 'fabricator' | 'false_ceiling' | 'ac_hvac' | 'glass_works' | 'polisher' | 'general_labour' | 'supervisor' | 'other'
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          phone?: string
          trade?: 'electrician' | 'carpenter' | 'painter' | 'plumber' | 'mason' | 'tiler' | 'fabricator' | 'false_ceiling' | 'ac_hvac' | 'glass_works' | 'polisher' | 'general_labour' | 'supervisor' | 'other'
          is_active?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      project_workers: {
        Row: {
          id: string
          project_id: string
          worker_id: string
          added_by: string | null
          workers_needed: number
          is_active: boolean
          added_at: string
        }
        Insert: {
          id?: string
          project_id: string
          worker_id: string
          added_by?: string | null
          workers_needed?: number
          is_active?: boolean
          added_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          worker_id?: string
          added_by?: string | null
          workers_needed?: number
          is_active?: boolean
          added_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_workers_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'project_workers_worker_id_fkey'
            columns: ['worker_id']
            isOneToOne: false
            referencedRelation: 'workers'
            referencedColumns: ['id']
          }
        ]
      }
      site_updates: {
        Row: {
          id: string
          project_id: string
          posted_by: string
          update_text: string
          workers_present: string[]
          worker_count: number
          photos: string[]
          update_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          posted_by: string
          update_text: string
          workers_present?: string[]
          worker_count?: number
          photos?: string[]
          update_date?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          posted_by?: string
          update_text?: string
          workers_present?: string[]
          worker_count?: number
          photos?: string[]
          update_date?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'site_updates_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'site_updates_posted_by_fkey'
            columns: ['posted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      worker_payments: {
        Row: {
          id: string
          project_id: string
          worker_id: string
          amount: number
          payment_date: string
          payment_mode: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by: string | null
          description: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          worker_id: string
          amount: number
          payment_date?: string
          payment_mode?: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by?: string | null
          description?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          worker_id?: string
          amount?: number
          payment_date?: string
          payment_mode?: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by?: string | null
          description?: string | null
          created_at?: string
        }
        Relationships: []
      }
      vendor_payments: {
        Row: {
          id: string
          project_id: string
          vendor_name: string
          item_description: string
          amount: number
          payment_date: string
          payment_mode: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by: string | null
          bill_photo_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          vendor_name: string
          item_description: string
          amount: number
          payment_date?: string
          payment_mode?: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by?: string | null
          bill_photo_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          vendor_name?: string
          item_description?: string
          amount?: number
          payment_date?: string
          payment_mode?: 'cash' | 'upi' | 'bank_transfer' | 'cheque' | null
          paid_by?: string | null
          bill_photo_url?: string | null
          created_at?: string
        }
        Relationships: []
      }
      project_documents: {
        Row: {
          id: string
          project_id: string
          uploaded_by: string | null
          file_name: string
          file_url: string
          file_type: 'drawing' | 'boq' | 'contract' | 'proposal' | 'invoice' | 'photo' | 'other' | null
          file_size_bytes: number | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          uploaded_by?: string | null
          file_name: string
          file_url: string
          file_type?: 'drawing' | 'boq' | 'contract' | 'proposal' | 'invoice' | 'photo' | 'other' | null
          file_size_bytes?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          uploaded_by?: string | null
          file_name?: string
          file_url?: string
          file_type?: 'drawing' | 'boq' | 'contract' | 'proposal' | 'invoice' | 'photo' | 'other' | null
          file_size_bytes?: number | null
          created_at?: string
        }
        Relationships: []
      }
      leads: {
        Row: {
          id: string
          full_name: string
          email: string | null
          phone: string
          city: string | null
          project_type: string | null
          budget_range: string | null
          message: string | null
          source_page: string
          status: 'new' | 'seen' | 'converted'
          converted_to_client_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          full_name: string
          email?: string | null
          phone: string
          city?: string | null
          project_type?: string | null
          budget_range?: string | null
          message?: string | null
          source_page?: string
          status?: 'new' | 'seen' | 'converted'
          converted_to_client_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          email?: string | null
          phone?: string
          city?: string | null
          project_type?: string | null
          budget_range?: string | null
          message?: string | null
          source_page?: string
          status?: 'new' | 'seen' | 'converted'
          converted_to_client_id?: string | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_partner: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']

export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']

export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
