import { StyleSheet } from '@react-pdf/renderer'

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    padding: 40,
    color: '#1C1C1A',
    backgroundColor: '#FFFFFF',
  },
  header: { marginBottom: 24 },
  firmName: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#B8955A' },
  firmTagline: { fontSize: 9, color: '#8C8680', marginTop: 2 },
  reportTitle: { fontSize: 14, fontFamily: 'Helvetica-Bold', marginTop: 16, marginBottom: 4 },
  reportSubtitle: { fontSize: 10, color: '#6B6966' },
  divider: { borderBottomWidth: 0.5, borderBottomColor: '#E5E3DF', marginVertical: 12 },
  sectionTitle: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginBottom: 8, marginTop: 16 },
  table: { width: '100%' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#F8F8F6', borderBottomWidth: 0.5, borderBottomColor: '#E5E3DF', paddingVertical: 6, paddingHorizontal: 8 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#F0EDEA', paddingVertical: 6, paddingHorizontal: 8 },
  tableHeaderCell: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: '#6B6966' },
  tableCell: { fontSize: 9, color: '#1C1C1A' },
  totalRow: { flexDirection: 'row', backgroundColor: '#FAF9F7', borderTopWidth: 1, borderTopColor: '#B8955A', paddingVertical: 8, paddingHorizontal: 8 },
  totalCell: { fontSize: 10, fontFamily: 'Helvetica-Bold' },
  summaryBox: { backgroundColor: '#FAF9F7', padding: 12, marginBottom: 16 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
  summaryLabel: { fontSize: 9, color: '#6B6966' },
  summaryValue: { fontSize: 9, fontFamily: 'Helvetica-Bold' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, flexDirection: 'row', justifyContent: 'space-between' },
  footerText: { fontSize: 8, color: '#8C8680' },
  pageNumber: { fontSize: 8, color: '#8C8680' },
  goldAccent: { color: '#B8955A' },
  dangerText: { color: '#B91C1C' },
  successText: { color: '#2D7D4F' },
})
